### ISSUE TITLE
Request fix for mtp function

### ISSUE THREAD

**Issue by MrRob0-X** [ace2nutzer/Samsung_dreamlte_Kernel#1]
facing this when compiling mtp function as "y"
**Link**: https://del.dog/agneppallo.txt

**Comment by ace2nutzer** [comment]
This was and still is a fix for TWRP mtp.
Just compile as modules, copy in proper folder and load modules like this:

    # load mtp - ptp module for stock ROM
    insmod /system/lib/modules/usb_f_mtp_samsung.ko // use usb_f_mtp.ko for non stock ROM
    insmod /system/lib/modules/usb_f_ptp.ko

If you build this kernel for TWRP then ...

    # load mtp module for TWRP
    insmod /lib/modules/usb_f_mtp.ko

**Comment by MrRob0-X** [comment]
I don't wanna make them as module, just as default 

hope there's solution for that

**Comment by ace2nutzer** [comment]
You get compile error because it's not possible to build MTP-(AOSP) and MTP-SAMSUNG together in just one driver.
As module it's possible since we will only load the one or the other.
Therefore you should decide which MTP variant to build built-in and comment out the other that you don't need here:

https://github.com/ace2nutzer/Samsung_dreamlte_Kernel/blob/master/drivers/usb/gadget/function/Makefile#L51

So comment out line #L52 + #L53 or #L55 + #L56.
Let me know if it worked for you, then i can close this "issue".

**Comment by MrRob0-X** [comment]
what if u did like that?

usb_f_mtp-y                                    := f_mtp.o
obj-$(CONFIG_USB_F_MTP)         += usb_f_mtp.o
else
elseusb_f_mtp_samsung-y	            := f_mtp_samsung.o
obj-$(CONFIG_USB_F_MTP)         += usb_f_mtp_samsung.o
endif

**Comment by MrRob0-X** [comment]
Fixed by revert what u edited: https://github.com/Neternels/Samsung_dreamlte_Kernel/commit/ef1043d931bfeac38188242be7927bd20e3dc210

**Comment by ace2nutzer** [comment]
Yeah, that works as well.
btw: i suggest to fetch your repo, otherwise it's possible that it won't boot at all.
